name: Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.6
        uses: actions/setup-python@v3
        with:
          python-version: 3.6

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dictionaries
        run: sudo apt-get install wamerican-huge wbritish-huge

      - name: Run tests
        run: |
          pipenv install --dev
          pipenv run pytest

  pre_commit:
    name: pre-commit
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.6

    - name: Install dictionaries
      run: sudo apt-get install wamerican-huge wbritish-huge

    - name: Run pre-commit
      uses: pre-commit/action@v2.0.3
